services:
  postgres:
    image: postgres:15-alpine
    container_name: recipe-planner-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: recipe_planner
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_user -d recipe_planner"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
