apiVersion: v1
kind: ConfigMap
metadata:
  name: recipe-planner-config
  namespace: recipe-planner
data:
  NODE_ENV: "production"
  APP_PORT: "3000"
  POSTGRES_DB: "recipe_planner"
  POSTGRES_USER: "recipe_user"
  POSTGRES_PORT: "5432"
  REDIS_PORT: "6379"