apiVersion: v1
kind: Secret
metadata:
  name: recipe-planner-secrets
  namespace: recipe-planner
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # To encode: echo -n "your-value" | base64
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=  # Replace with base64 encoded password
  FIREBASE_API_KEY: eW91ci1maXJlYmFzZS1hcGkta2V5  # Replace with base64 encoded API key
  FIREBASE_AUTH_DOMAIN: eW91ci1wcm9qZWN0LmZpcmViYXNlYXBwLmNvbQ==  # Replace with base64 encoded domain
  FIREBASE_PROJECT_ID: eW91ci1wcm9qZWN0LWlk  # Replace with base64 encoded project ID
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==  # Replace with base64 encoded JWT secret
  ENCRYPTION_KEY: eW91ci0zMi1jaGFyYWN0ZXItZW5jcnlwdGlvbi1rZXk=  # Replace with base64 encoded encryption key